name: StariteCore
version: '${project.version}'
main: me.zenzoyaudr.staritecore.Main
api-version: 1.16
authors: [ ZenZoyaUDR ]
commands:
  test:
    description: A simple test command
  menu:
    description: A test gui